name: Build and Publish
on:
  push:
    tags: '*'
permissions:
  id-token: write  # Required for OIDC
  contents: read
jobs:
  all:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish ./pkg
